openldap:
  image: oriaks/openldap:latest
  environment:
    LDAP_DOMAIN: localhost
    LDAP_ORGANIZATION: Localhost
    LDAP_PASSWORD: admin
  restart: unless-stopped
  volumes:
    - ./volumes/openldap/config:/etc/ldap/slapd.d:rw
    - ./volumes/openldap/data:/var/lib/ldap:rw

nginx:
  image: oriaks/nginx:latest
  ports:
    - 0.0.0.0:80:80/tcp
    - 0.0.0.0:443:443/tcp
  restart: unless-stopped
  volumes:
    - /etc/nginx
    - ./volumes/nginx/config/cert.d:/etc/nginx/cert.d:rw
    - ./volumes/nginx/log:/var/log/nginx:rw

docker-gen:
  image: oriaks/docker-gen:latest
  command: -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  links:
    - nginx
  restart: unless-stopped
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  volumes_from:
    - nginx:rw

phpldapadmin:
  image: oriaks/phpldapadmin:latest
  environment:
    VIRTUAL_HOST: localhost
    VIRTUAL_PROTO: https
    VIRTUAL_PORT: 443
    FORCE_HTTPS: 'true'
  expose:
    - 443/tcp
  links:
    - openldap:ldap
  restart: unless-stopped

freeswitch:
  image: oriaks/freeswitch:latest
  environment:
    SIP_DOMAIN: localhost
  expose:
    - 5060/tcp
    - 5060/udp
  links:
    - openldap:ldap
  ports:
    - 0.0.0.0:5060:5060/tcp
    - 0.0.0.0:5060:5060/udp
  restart: unless-stopped
  volumes:
    - ./volumes/freeswitch/data:/var/lib/freeswitch:rw

coturn:
  image: oriaks/coturn:latest
  expose:
    - 3478/tcp
    - 3478/udp
  links:
    - openldap:ldap
  ports:
    - 0.0.0.0:3478:3478/tcp
    - 0.0.0.0:3478:3478/udp
  restart: unless-stopped
  volumes:
    - ./volumes/coturn/data:/var/lib/turn:rw
